#!/usr/bin/env bash
# This script displays username, user id, and home directory from /etc/passwd

while IFS=: read -r username password userid groupid userinfo homedir shell
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
