#!/usr/bin/env bash
# Script that displays a list of currently running processes
# Shows all processes, for all users, including those without TTY
# Display in user-oriented format with process hierarchy
ps auxf
