#!/usr/bin/env bash
# Script that creates PID file, displays messages indefinitely,
# and handles different signals appropriately

PID_FILE=${PID_FILE:-/var/run/my_process.pid}

sigterm_handler() {
    echo "I hate the kill command"
    rm -f "$PID_FILE"
    exit 0
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    rm -f "$PID_FILE"
    exit 0
}

echo $$ > "$PID_FILE"

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done

