#!/usr/bin/env bash
# Script that creates PID file, displays messages indefinitely,
# and handles different signals appropriately

# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
sigint_handler() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
sigquit_handler() {
    rm -f /var/run/myscript.pid
    exit 0
}

# Create PID file
echo $$ > /var/run/myscript.pid

# Trap signals
trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
